services:
  client:
    image: 982534376867.dkr.ecr.ap-south-1.amazonaws.com/tutorial-hell-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - server
    restart: unless-stopped

  server:
    image: 982534376867.dkr.ecr.ap-south-1.amazonaws.com/tutorial-hell-backend:latest
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=harsh1592
      - DB_NAME=youtube
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_CALLBACK_URL=https://youtube.harshthakur.site/api/auth/callback?provider=google
      - REDIRECT_SECURE=https://youtube.harshthakur.site
      - SESSION_COOKIE_DOMAIN=youtube.harshthakur.site
      - ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harsh1592
      POSTGRES_DB: youtube
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
